name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Test echo
      run: echo "Running tests in test_git_personal Repo"
    - name: Display the build.properties
      run: cat project/build.properties
    - name: Finish Test echo
      run: echo "Completed tests in test_git_personal Repo"
    - name: Docker Build
      run: docker build -t karthikt/myimage .
    - name: Docker run
      run: docker run karthikt/myimage Arjun
    - name: Run Assembly
      run: sbt assembly
